version: "3.8"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    ports:
      - 8080:8080
    depends_on:
      - pg-db
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - learnhub-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cache:
    image: redis:7.2.3
    expose:
      - 6379
volumes:
  learnhub-db-vol:
    name: 76bc8800775fa6fd022c82e44760ef14ed81ff84b29dd4c6c235ddfd4b6b9ade
