name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Echo hello-world
        run: echo "Hello, world."
      - name: Where now!!
        run: pwd
      - name: list
        run: ls
